name: Run every minute

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    name: Cron Job
    runs-on: ubuntu-latest

    steps:
      - name: Hello world action step
        run: echo :"Hello world!"